const sqlite3 = require("sqlite3").verbose();
const path = require("path");
const fs = require("fs");

const dataDir = path.join(__dirname, "..", "data");
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

const dbPath = path.join(dataDir, "diverseev.db");
const db = new sqlite3.Database(dbPath);

function initTables() {
  db.serialize(() => {
    db.run(`CREATE TABLE IF NOT EXISTS vehicles (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      brand TEXT NOT NULL,
      category TEXT NOT NULL,
      curb_weight INTEGER NOT NULL,
      range INTEGER NOT NULL,
      price REAL NOT NULL,
      scenarios TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT '在售',
      material TEXT,
      energy_density REAL,
      launch_year INTEGER,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS tech_progress (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      type TEXT NOT NULL,
      name TEXT NOT NULL,
      description TEXT,
      weight_reduction REAL,
      efficiency_improvement REAL,
      maturity_level TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS tier_trend_stats (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      stat_date TEXT NOT NULL,
      tier_name TEXT NOT NULL,
      vehicle_count INTEGER NOT NULL DEFAULT 0,
      indicator_type TEXT NOT NULL DEFAULT 'weight',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS annual_diversity_stats (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      stat_year INTEGER NOT NULL,
      total_vehicles INTEGER NOT NULL DEFAULT 0,
      diversity_score REAL NOT NULL DEFAULT 0,
      micro_count INTEGER DEFAULT 0,
      compact_count INTEGER DEFAULT 0,
      midsize_count INTEGER DEFAULT 0,
      commercial_count INTEGER DEFAULT 0,
      micro_ratio REAL DEFAULT 0,
      compact_ratio REAL DEFAULT 0,
      midsize_ratio REAL DEFAULT 0,
      commercial_ratio REAL DEFAULT 0,
      avg_weight REAL DEFAULT 0,
      heavy_ratio REAL DEFAULT 0,
      brand_count INTEGER DEFAULT 0,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(stat_year)
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS regions (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      name TEXT NOT NULL,
      code TEXT NOT NULL,
      terrain_type TEXT NOT NULL,
      climate TEXT,
      typical_usage TEXT,
      description TEXT,
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      UNIQUE(code)
    )`);

    db.run(`CREATE TABLE IF NOT EXISTS region_vehicle_requirements (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      region_id INTEGER NOT NULL,
      category TEXT NOT NULL,
      min_range INTEGER,
      max_range INTEGER,
      min_weight INTEGER,
      max_weight INTEGER,
      min_price REAL,
      max_price REAL,
      terrain_suitability TEXT,
      priority INTEGER DEFAULT 0,
      required_scenarios TEXT,
      FOREIGN KEY (region_id) REFERENCES regions(id),
      UNIQUE(region_id, category)
    )`);

    console.log("数据表初始化完成");
  });
}

const vehicleLaunchYears = {
  五菱宏光MINIEV: 2020,
  五菱缤果: 2023,
  比亚迪海鸥: 2023,
  长安Lumin: 2022,
  奇瑞QQ冰淇淋: 2021,
  奇瑞无界Pro: 2022,
  吉利熊猫mini: 2023,
  几何E萤火虫: 2024,
  哪吒AYA: 2023,
  零跑T03: 2020,
  思皓花仙子: 2021,
  江南U2: 2023,
  风光MINIEV: 2022,
  小虎FEV: 2021,
  北汽制造家宝: 2023,
  奔腾小马: 2024,
  雷丁芒果: 2021,
  荣威科莱威: 2020,
  "smart精灵#1": 2022,
  比亚迪海豚: 2021,
  欧拉好猫: 2020,
  哪吒S: 2022,
  零跑C11: 2021,
  广汽埃安Y: 2021,
  广汽埃安S: 2019,
  小鹏G6: 2023,
  小鹏P7i: 2023,
  "特斯拉Model 3": 2019,
  "特斯拉Model Y": 2021,
  比亚迪元PLUS: 2022,
  "比亚迪宋PLUS EV": 2021,
  "比亚迪秦PLUS EV": 2021,
  吉利几何C: 2020,
  "吉利帝豪L HiP": 2022,
  吉利银河E5: 2024,
  "上汽大众ID.3": 2021,
  "上汽大众ID.4 X": 2021,
  "一汽-大众ID.4 CROZZ": 2021,
  "一汽-大众ID.6 CROZZ": 2021,
  上汽通用别克E5: 2023,
  极氪X: 2023,
  极氪001: 2021,
  极氪007: 2023,
  蔚来ES6: 2023,
  蔚来ES8: 2020,
  蔚来ET5: 2022,
  蔚来ET5T: 2023,
  蔚来ET7: 2021,
  理想L7: 2023,
  理想L8: 2022,
  理想L9: 2022,
  理想MEGA: 2024,
  问界M5: 2022,
  问界M7: 2022,
  问界M9: 2023,
  智己L7: 2022,
  智己LS6: 2023,
  智己LS7: 2023,
  飞凡F7: 2023,
  飞凡R7: 2022,
  "高合HiPhi X": 2020,
  "高合HiPhi Z": 2022,
  "高合HiPhi Y": 2023,
  腾势D9: 2022,
  腾势N7: 2023,
  腾势N8: 2023,
  比亚迪汉EV: 2020,
  比亚迪唐EV: 2021,
  比亚迪海豹: 2022,
  "比亚迪海豹DM-i": 2023,
  比亚迪护卫舰07: 2022,
  仰望U8: 2023,
  仰望U9: 2024,
  "特斯拉Model S": 2019,
  "特斯拉Model X": 2019,
  宝马i3: 2022,
  宝马i4: 2022,
  宝马iX3: 2020,
  宝马iX: 2021,
  奔驰EQE: 2022,
  奔驰EQS: 2021,
  "奥迪e-tron": 2020,
  "奥迪Q4 e-tron": 2022,
  "奥迪Q5 e-tron": 2022,
  凯迪拉克锐歌: 2022,
  沃尔沃XC40纯电: 2021,
  沃尔沃C40: 2022,
  福特电马: 2021,
  捷尼赛思GV60: 2023,
  捷尼赛思纯电G80: 2022,
  捷尼赛思纯电GV70: 2022,
  雷克萨斯RZ: 2023,
  "英菲尼迪QX Inspiration": 2025,
  极狐阿尔法S: 2021,
  极狐阿尔法T: 2021,
  岚图FREE: 2021,
  岚图追光: 2023,
  岚图梦想家: 2022,
  魏牌蓝山: 2023,
  魏牌高山: 2023,
  小鹏X9: 2023,
  东风御风EM26: 2021,
  远程星享V: 2022,
  远程星智H: 2022,
  远程锋锐F3E: 2021,
  远程超级VAN: 2023,
  宇通新能源轻卡: 2021,
  宇通新能源客车: 2020,
  宇通T7新能源: 2022,
  北汽EV5: 2020,
  北汽瑞驰EC35: 2020,
  瑞驰EC31: 2021,
  开瑞海豚EV: 2020,
  开瑞优优EV: 2020,
  五菱EV50: 2021,
  五菱宏光EV: 2022,
  新龙马启腾N50: 2021,
  吉利远程E6: 2022,
  比亚迪T5: 2021,
  比亚迪T4: 2022,
  比亚迪商用车T3: 2020,
  "长安跨越王X1 EV": 2021,
  "长安神骐T10 EV": 2020,
  "江淮恺达X6 EV": 2022,
  江淮帅铃i5: 2021,
  庆铃五十铃EVK1: 2022,
  "东风柳汽乘龙L2 EV": 2023,
  重汽豪沃智相: 2022,
  陕汽德龙E3000: 2022,
  欧曼智蓝: 2023,
  解放J6L纯电: 2022,
  "东风天锦KR EV": 2023,
  比亚迪纯电动大巴: 2020,
  金龙纯电动客车: 2020,
  中通纯电动客车: 2020,
  安凯纯电动客车: 2020,
  宁德时代换电重卡: 2025,
  特斯拉Semi: 2025,
  Cybertruck: 2025,
  起亚EV6: 2021,
  "现代IONIQ 5": 2021,
  雪佛兰畅巡: 2020,
  雪佛兰探界者EV: 2025,
  "本田e:NS1": 2022,
  丰田bZ4X: 2022,
  丰田bZ3: 2023,
  日产Ariya: 2022,
  斯巴鲁Solterra: 2022,
  "马自达MX-30": 2020,
  "雪铁龙凡尔赛C5 X PHEV": 2021,
  "标致408X PHEV": 2022,
  "DS 9新能源": 2021,
  极星2: 2020,
  极星3: 2023,
  路特斯Eletre: 2023,
  保时捷Taycan: 2020,
  "奥迪RS e-tron GT": 2021,
  "奔驰EQE SUV": 2023,
  雷克萨斯RX新能源: 2023,
  雷克萨斯RZ450e: 2023,
  沃尔沃EX90: 2025,
  沃尔沃EX30: 2025,
  "smart精灵#3": 2023,
  "smart精灵#5": 2025,
  "福特野马Mach-E": 2021,
  "福特F-150 Lightning": 2022,
  悍马EV: 2022,
  "雪佛兰Silverado EV": 2025,
  "RAM 1500 REV": 2025,
  "Scioniq 7": 2025,
  起亚EV9: 2025,
  "日产Max-Out": 2025,
};

const vehicles = [
  {
    name: "五菱宏光MINIEV",
    brand: "五菱",
    category: "微型代步",
    curb_weight: 705,
    range: 170,
    price: 3.28,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 120,
    launch_year: vehicleLaunchYears["五菱宏光MINIEV"],
  },
  {
    name: "五菱缤果",
    brand: "五菱",
    category: "微型代步",
    curb_weight: 990,
    range: 333,
    price: 5.98,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "比亚迪海鸥",
    brand: "比亚迪",
    category: "微型代步",
    curb_weight: 1160,
    range: 305,
    price: 7.38,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 150,
  },
  {
    name: "长安Lumin",
    brand: "长安",
    category: "微型代步",
    curb_weight: 985,
    range: 301,
    price: 4.99,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "奇瑞QQ冰淇淋",
    brand: "奇瑞",
    category: "微型代步",
    curb_weight: 743,
    range: 170,
    price: 3.99,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 115,
  },
  {
    name: "奇瑞无界Pro",
    brand: "奇瑞",
    category: "微型代步",
    curb_weight: 1115,
    range: 301,
    price: 8.99,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 145,
  },
  {
    name: "吉利熊猫mini",
    brand: "吉利",
    category: "微型代步",
    curb_weight: 885,
    range: 200,
    price: 3.99,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 125,
  },
  {
    name: "几何E萤火虫",
    brand: "吉利",
    category: "微型代步",
    curb_weight: 1275,
    range: 401,
    price: 6.98,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 155,
  },
  {
    name: "哪吒AYA",
    brand: "哪吒",
    category: "微型代步",
    curb_weight: 1185,
    range: 401,
    price: 7.38,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 150,
  },
  {
    name: "零跑T03",
    brand: "零跑",
    category: "微型代步",
    curb_weight: 1122,
    range: 403,
    price: 5.99,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 160,
  },
  {
    name: "思皓花仙子",
    brand: "思皓",
    category: "微型代步",
    curb_weight: 1055,
    range: 306,
    price: 6.99,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "江南U2",
    brand: "江南",
    category: "微型代步",
    curb_weight: 1030,
    range: 305,
    price: 5.88,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "风光MINIEV",
    brand: "东风风光",
    category: "微型代步",
    curb_weight: 810,
    range: 220,
    price: 3.96,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 120,
  },
  {
    name: "小虎FEV",
    brand: "小虎",
    category: "微型代步",
    curb_weight: 920,
    range: 215,
    price: 4.19,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 118,
  },
  {
    name: "北汽制造家宝",
    brand: "北汽制造",
    category: "微型代步",
    curb_weight: 960,
    range: 205,
    price: 4.69,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 122,
  },
  {
    name: "奔腾小马",
    brand: "奔腾",
    category: "微型代步",
    curb_weight: 830,
    range: 170,
    price: 3.69,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 115,
  },
  {
    name: "雷丁芒果",
    brand: "雷丁",
    category: "微型代步",
    curb_weight: 1150,
    range: 335,
    price: 5.98,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "荣威科莱威",
    brand: "荣威",
    category: "微型代步",
    curb_weight: 1050,
    range: 311,
    price: 5.99,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 138,
  },
  {
    name: "smart精灵#1",
    brand: "smart",
    category: "家用紧凑",
    curb_weight: 1775,
    range: 535,
    price: 17.9,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 175,
  },
  {
    name: "比亚迪海豚",
    brand: "比亚迪",
    category: "家用紧凑",
    curb_weight: 1505,
    range: 420,
    price: 11.68,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 160,
  },
  {
    name: "欧拉好猫",
    brand: "欧拉",
    category: "家用紧凑",
    curb_weight: 1555,
    range: 501,
    price: 12.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 165,
  },
  {
    name: "哪吒S",
    brand: "哪吒",
    category: "家用紧凑",
    curb_weight: 1820,
    range: 520,
    price: 15.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 170,
  },
  {
    name: "零跑C11",
    brand: "零跑",
    category: "家用紧凑",
    curb_weight: 1995,
    range: 550,
    price: 14.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 180,
  },
  {
    name: "广汽埃安Y",
    brand: "埃安",
    category: "家用紧凑",
    curb_weight: 1765,
    range: 510,
    price: 11.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 172,
  },
  {
    name: "广汽埃安S",
    brand: "埃安",
    category: "家用紧凑",
    curb_weight: 1665,
    range: 510,
    price: 13.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "小鹏G6",
    brand: "小鹏",
    category: "家用紧凑",
    curb_weight: 1930,
    range: 580,
    price: 20.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 185,
  },
  {
    name: "小鹏P7i",
    brand: "小鹏",
    category: "家用紧凑",
    curb_weight: 1910,
    range: 610,
    price: 20.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 180,
  },
  {
    name: "特斯拉Model 3",
    brand: "特斯拉",
    category: "家用紧凑",
    curb_weight: 1760,
    range: 556,
    price: 23.19,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 217,
  },
  {
    name: "特斯拉Model Y",
    brand: "特斯拉",
    category: "家用紧凑",
    curb_weight: 1995,
    range: 545,
    price: 26.39,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 217,
  },
  {
    name: "比亚迪元PLUS",
    brand: "比亚迪",
    category: "家用紧凑",
    curb_weight: 1690,
    range: 510,
    price: 12.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 165,
  },
  {
    name: "比亚迪宋PLUS EV",
    brand: "比亚迪",
    category: "家用紧凑",
    curb_weight: 1860,
    range: 520,
    price: 15.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 168,
  },
  {
    name: "比亚迪秦PLUS EV",
    brand: "比亚迪",
    category: "家用紧凑",
    curb_weight: 1720,
    range: 510,
    price: 12.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 165,
  },
  {
    name: "吉利几何C",
    brand: "吉利",
    category: "家用紧凑",
    curb_weight: 1665,
    range: 550,
    price: 12.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 168,
  },
  {
    name: "吉利帝豪L HiP",
    brand: "吉利",
    category: "家用紧凑",
    curb_weight: 1780,
    range: 100,
    price: 10.98,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 150,
  },
  {
    name: "吉利银河E5",
    brand: "吉利",
    category: "家用紧凑",
    curb_weight: 1820,
    range: 530,
    price: 14.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 175,
  },
  {
    name: "上汽大众ID.3",
    brand: "大众",
    category: "家用紧凑",
    curb_weight: 1760,
    range: 450,
    price: 14.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "上汽大众ID.4 X",
    brand: "大众",
    category: "家用紧凑",
    curb_weight: 1960,
    range: 555,
    price: 19.59,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "一汽-大众ID.4 CROZZ",
    brand: "大众",
    category: "家用紧凑",
    curb_weight: 1940,
    range: 550,
    price: 19.39,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "一汽-大众ID.6 CROZZ",
    brand: "大众",
    category: "家用紧凑",
    curb_weight: 2120,
    range: 565,
    price: 23.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 178,
  },
  {
    name: "上汽通用别克E5",
    brand: "别克",
    category: "家用紧凑",
    curb_weight: 2115,
    range: 545,
    price: 16.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 168,
  },
  {
    name: "极氪X",
    brand: "极氪",
    category: "家用紧凑",
    curb_weight: 1945,
    range: 560,
    price: 18.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "极氪001",
    brand: "极氪",
    category: "中大型",
    curb_weight: 2223,
    range: 741,
    price: 30.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 190,
  },
  {
    name: "极氪007",
    brand: "极氪",
    category: "中大型",
    curb_weight: 2065,
    range: 688,
    price: 20.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 195,
  },
  {
    name: "蔚来ES6",
    brand: "蔚来",
    category: "中大型",
    curb_weight: 2200,
    range: 625,
    price: 36.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 180,
  },
  {
    name: "蔚来ES8",
    brand: "蔚来",
    category: "中大型",
    curb_weight: 2460,
    range: 605,
    price: 49.6,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 185,
  },
  {
    name: "蔚来ET5",
    brand: "蔚来",
    category: "中大型",
    curb_weight: 2185,
    range: 590,
    price: 32.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 185,
  },
  {
    name: "蔚来ET5T",
    brand: "蔚来",
    category: "中大型",
    curb_weight: 2240,
    range: 590,
    price: 29.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 185,
  },
  {
    name: "蔚来ET7",
    brand: "蔚来",
    category: "中大型",
    curb_weight: 2380,
    range: 675,
    price: 42.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 190,
  },
  {
    name: "理想L7",
    brand: "理想",
    category: "中大型",
    curb_weight: 2450,
    range: 210,
    price: 31.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 170,
  },
  {
    name: "理想L8",
    brand: "理想",
    category: "中大型",
    curb_weight: 2515,
    range: 210,
    price: 33.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 170,
  },
  {
    name: "理想L9",
    brand: "理想",
    category: "中大型",
    curb_weight: 2570,
    range: 215,
    price: 42.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 170,
  },
  {
    name: "理想MEGA",
    brand: "理想",
    category: "中大型",
    curb_weight: 2785,
    range: 700,
    price: 55.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 180,
  },
  {
    name: "问界M5",
    brand: "AITO",
    category: "中大型",
    curb_weight: 2225,
    range: 255,
    price: 24.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 170,
  },
  {
    name: "问界M7",
    brand: "AITO",
    category: "中大型",
    curb_weight: 2390,
    range: 240,
    price: 24.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 168,
  },
  {
    name: "问界M9",
    brand: "AITO",
    category: "中大型",
    curb_weight: 2610,
    range: 225,
    price: 46.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 175,
  },
  {
    name: "智己L7",
    brand: "智己",
    category: "中大型",
    curb_weight: 2290,
    range: 615,
    price: 29.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 190,
  },
  {
    name: "智己LS6",
    brand: "智己",
    category: "中大型",
    curb_weight: 2125,
    range: 680,
    price: 21.49,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 195,
  },
  {
    name: "智己LS7",
    brand: "智己",
    category: "中大型",
    curb_weight: 2460,
    range: 660,
    price: 28.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 190,
  },
  {
    name: "飞凡F7",
    brand: "飞凡",
    category: "中大型",
    curb_weight: 2060,
    range: 600,
    price: 20.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "飞凡R7",
    brand: "飞凡",
    category: "中大型",
    curb_weight: 2200,
    range: 642,
    price: 18.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "高合HiPhi X",
    brand: "高合",
    category: "中大型",
    curb_weight: 2500,
    range: 560,
    price: 57.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 180,
  },
  {
    name: "高合HiPhi Z",
    brand: "高合",
    category: "中大型",
    curb_weight: 2539,
    range: 705,
    price: 61.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 190,
  },
  {
    name: "高合HiPhi Y",
    brand: "高合",
    category: "中大型",
    curb_weight: 2430,
    range: 810,
    price: 33.9,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 195,
  },
  {
    name: "腾势D9",
    brand: "腾势",
    category: "中大型",
    curb_weight: 2689,
    range: 190,
    price: 33.58,
    scenarios: ["城市通勤", "长途", "载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "腾势N7",
    brand: "腾势",
    category: "中大型",
    curb_weight: 2320,
    range: 630,
    price: 30.18,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "腾势N8",
    brand: "腾势",
    category: "中大型",
    curb_weight: 2430,
    range: 216,
    price: 31.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "比亚迪汉EV",
    brand: "比亚迪",
    category: "中大型",
    curb_weight: 2195,
    range: 715,
    price: 20.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 185,
  },
  {
    name: "比亚迪唐EV",
    brand: "比亚迪",
    category: "中大型",
    curb_weight: 2325,
    range: 635,
    price: 24.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 180,
  },
  {
    name: "比亚迪海豹",
    brand: "比亚迪",
    category: "中大型",
    curb_weight: 1920,
    range: 700,
    price: 18.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "比亚迪海豹DM-i",
    brand: "比亚迪",
    category: "中大型",
    curb_weight: 2025,
    range: 1120,
    price: 16.68,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 160,
  },
  {
    name: "比亚迪护卫舰07",
    brand: "比亚迪",
    category: "中大型",
    curb_weight: 2225,
    range: 205,
    price: 20.28,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 165,
  },
  {
    name: "仰望U8",
    brand: "仰望",
    category: "中大型",
    curb_weight: 3460,
    range: 1000,
    price: 109.8,
    scenarios: ["城市通勤", "长途", "载货"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 175,
  },
  {
    name: "仰望U9",
    brand: "仰望",
    category: "中大型",
    curb_weight: 1990,
    range: 450,
    price: 168.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "碳纤维+铝合金",
    energy_density: 200,
  },
  {
    name: "特斯拉Model S",
    brand: "特斯拉",
    category: "中大型",
    curb_weight: 2060,
    range: 652,
    price: 78.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 217,
  },
  {
    name: "特斯拉Model X",
    brand: "特斯拉",
    category: "中大型",
    curb_weight: 2270,
    range: 580,
    price: 87.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 217,
  },
  {
    name: "宝马i3",
    brand: "宝马",
    category: "中大型",
    curb_weight: 2095,
    range: 526,
    price: 35.39,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "宝马i4",
    brand: "宝马",
    category: "中大型",
    curb_weight: 2120,
    range: 560,
    price: 42.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 188,
  },
  {
    name: "宝马iX3",
    brand: "宝马",
    category: "中大型",
    curb_weight: 2115,
    range: 550,
    price: 39.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 185,
  },
  {
    name: "宝马iX",
    brand: "宝马",
    category: "中大型",
    curb_weight: 2510,
    range: 665,
    price: 74.69,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金+碳纤维",
    energy_density: 195,
  },
  {
    name: "奔驰EQE",
    brand: "奔驰",
    category: "中大型",
    curb_weight: 2355,
    range: 752,
    price: 47.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "奔驰EQS",
    brand: "奔驰",
    category: "中大型",
    curb_weight: 2585,
    range: 849,
    price: 84.5,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 195,
  },
  {
    name: "奥迪e-tron",
    brand: "奥迪",
    category: "中大型",
    curb_weight: 2585,
    range: 500,
    price: 66.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "奥迪Q4 e-tron",
    brand: "奥迪",
    category: "中大型",
    curb_weight: 2180,
    range: 605,
    price: 28.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 180,
  },
  {
    name: "奥迪Q5 e-tron",
    brand: "奥迪",
    category: "中大型",
    curb_weight: 2260,
    range: 560,
    price: 37.65,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "凯迪拉克锐歌",
    brand: "凯迪拉克",
    category: "中大型",
    curb_weight: 2570,
    range: 653,
    price: 37.97,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "沃尔沃XC40纯电",
    brand: "沃尔沃",
    category: "中大型",
    curb_weight: 2108,
    range: 529,
    price: 26.7,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "沃尔沃C40",
    brand: "沃尔沃",
    category: "中大型",
    curb_weight: 2143,
    range: 530,
    price: 28.9,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "福特电马",
    brand: "福特",
    category: "中大型",
    curb_weight: 2205,
    range: 554,
    price: 24.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 180,
  },
  {
    name: "捷尼赛思GV60",
    brand: "捷尼赛思",
    category: "中大型",
    curb_weight: 2085,
    range: 638,
    price: 28.58,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "捷尼赛思纯电G80",
    brand: "捷尼赛思",
    category: "中大型",
    curb_weight: 2325,
    range: 625,
    price: 40.68,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "捷尼赛思纯电GV70",
    brand: "捷尼赛思",
    category: "中大型",
    curb_weight: 2310,
    range: 530,
    price: 38.58,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 180,
  },
  {
    name: "雷克萨斯RZ",
    brand: "雷克萨斯",
    category: "中大型",
    curb_weight: 2115,
    range: 520,
    price: 36.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "英菲尼迪QX Inspiration",
    brand: "英菲尼迪",
    category: "中大型",
    curb_weight: 2200,
    range: 500,
    price: 45.0,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 180,
  },
  {
    name: "极狐阿尔法S",
    brand: "极狐",
    category: "中大型",
    curb_weight: 2125,
    range: 708,
    price: 22.38,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "极狐阿尔法T",
    brand: "极狐",
    category: "中大型",
    curb_weight: 2280,
    range: 688,
    price: 21.88,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "岚图FREE",
    brand: "岚图",
    category: "中大型",
    curb_weight: 2290,
    range: 205,
    price: 26.69,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 160,
  },
  {
    name: "岚图追光",
    brand: "岚图",
    category: "中大型",
    curb_weight: 2240,
    range: 580,
    price: 32.29,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "岚图梦想家",
    brand: "岚图",
    category: "中大型",
    curb_weight: 2610,
    range: 236,
    price: 36.99,
    scenarios: ["城市通勤", "长途", "载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 165,
  },
  {
    name: "魏牌蓝山",
    brand: "魏牌",
    category: "中大型",
    curb_weight: 2480,
    range: 180,
    price: 27.38,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 160,
  },
  {
    name: "魏牌高山",
    brand: "魏牌",
    category: "中大型",
    curb_weight: 2615,
    range: 140,
    price: 33.58,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 155,
  },
  {
    name: "小鹏X9",
    brand: "小鹏",
    category: "中大型",
    curb_weight: 2630,
    range: 702,
    price: 35.98,
    scenarios: ["城市通勤", "长途", "载货"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "东风御风EM26",
    brand: "东风",
    category: "商用",
    curb_weight: 2580,
    range: 220,
    price: 16.88,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "远程星享V",
    brand: "远程",
    category: "商用",
    curb_weight: 2200,
    range: 260,
    price: 12.58,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "远程星智H",
    brand: "远程",
    category: "商用",
    curb_weight: 3200,
    range: 320,
    price: 22.88,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 145,
  },
  {
    name: "远程锋锐F3E",
    brand: "远程",
    category: "商用",
    curb_weight: 1860,
    range: 310,
    price: 18.98,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 145,
  },
  {
    name: "远程超级VAN",
    brand: "远程",
    category: "商用",
    curb_weight: 2450,
    range: 380,
    price: 18.88,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 150,
  },
  {
    name: "宇通新能源轻卡",
    brand: "宇通",
    category: "商用",
    curb_weight: 3300,
    range: 350,
    price: 25.98,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "宇通新能源客车",
    brand: "宇通",
    category: "商用",
    curb_weight: 10500,
    range: 450,
    price: 88.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "宇通T7新能源",
    brand: "宇通",
    category: "商用",
    curb_weight: 5200,
    range: 400,
    price: 68.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "北汽EV5",
    brand: "北汽",
    category: "商用",
    curb_weight: 2500,
    range: 270,
    price: 13.38,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "北汽瑞驰EC35",
    brand: "瑞驰",
    category: "商用",
    curb_weight: 2450,
    range: 300,
    price: 14.58,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "瑞驰EC31",
    brand: "瑞驰",
    category: "商用",
    curb_weight: 1650,
    range: 290,
    price: 12.98,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "开瑞海豚EV",
    brand: "开瑞",
    category: "商用",
    curb_weight: 2510,
    range: 251,
    price: 14.58,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "开瑞优优EV",
    brand: "开瑞",
    category: "商用",
    curb_weight: 2400,
    range: 260,
    price: 13.68,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "五菱EV50",
    brand: "五菱",
    category: "商用",
    curb_weight: 2610,
    range: 300,
    price: 14.38,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "五菱宏光EV",
    brand: "五菱",
    category: "商用",
    curb_weight: 1585,
    range: 255,
    price: 11.88,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "新龙马启腾N50",
    brand: "新龙马",
    category: "商用",
    curb_weight: 1520,
    range: 280,
    price: 12.38,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "吉利远程E6",
    brand: "吉利",
    category: "商用",
    curb_weight: 2300,
    range: 260,
    price: 16.28,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "比亚迪T5",
    brand: "比亚迪",
    category: "商用",
    curb_weight: 2350,
    range: 260,
    price: 18.98,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "比亚迪T4",
    brand: "比亚迪",
    category: "商用",
    curb_weight: 1600,
    range: 280,
    price: 16.58,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "比亚迪商用车T3",
    brand: "比亚迪",
    category: "商用",
    curb_weight: 2550,
    range: 250,
    price: 17.58,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "长安跨越王X1 EV",
    brand: "长安",
    category: "商用",
    curb_weight: 1420,
    range: 230,
    price: 11.88,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 125,
  },
  {
    name: "长安神骐T10 EV",
    brand: "长安",
    category: "商用",
    curb_weight: 1400,
    range: 220,
    price: 11.58,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 125,
  },
  {
    name: "江淮恺达X6 EV",
    brand: "江淮",
    category: "商用",
    curb_weight: 2750,
    range: 290,
    price: 17.98,
    scenarios: ["载货", "城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "江淮帅铃i5",
    brand: "江淮",
    category: "商用",
    curb_weight: 3400,
    range: 330,
    price: 23.98,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "庆铃五十铃EVK1",
    brand: "庆铃",
    category: "商用",
    curb_weight: 3200,
    range: 280,
    price: 26.98,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "东风柳汽乘龙L2 EV",
    brand: "东风",
    category: "商用",
    curb_weight: 4200,
    range: 280,
    price: 28.88,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "重汽豪沃智相",
    brand: "重汽",
    category: "商用",
    curb_weight: 3100,
    range: 260,
    price: 18.98,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "陕汽德龙E3000",
    brand: "陕汽",
    category: "商用",
    curb_weight: 4500,
    range: 280,
    price: 32.88,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "欧曼智蓝",
    brand: "福田",
    category: "商用",
    curb_weight: 5800,
    range: 350,
    price: 45.88,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "解放J6L纯电",
    brand: "解放",
    category: "商用",
    curb_weight: 5500,
    range: 300,
    price: 42.88,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "东风天锦KR EV",
    brand: "东风",
    category: "商用",
    curb_weight: 5800,
    range: 350,
    price: 48.88,
    scenarios: ["载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "比亚迪纯电动大巴",
    brand: "比亚迪",
    category: "商用",
    curb_weight: 12500,
    range: 500,
    price: 120.0,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "金龙纯电动客车",
    brand: "金龙",
    category: "商用",
    curb_weight: 11800,
    range: 480,
    price: 95.0,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "中通纯电动客车",
    brand: "中通",
    category: "商用",
    curb_weight: 11000,
    range: 450,
    price: 85.0,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "安凯纯电动客车",
    brand: "安凯",
    category: "商用",
    curb_weight: 11200,
    range: 460,
    price: 88.0,
    scenarios: ["城市通勤"],
    status: "在售",
    material: "高强度钢",
    energy_density: 130,
  },
  {
    name: "宁德时代换电重卡",
    brand: "宁德时代",
    category: "商用",
    curb_weight: 8500,
    range: 350,
    price: 68.0,
    scenarios: ["载货", "长途"],
    status: "待上市",
    material: "高强度钢",
    energy_density: 150,
  },
  {
    name: "特斯拉Semi",
    brand: "特斯拉",
    category: "商用",
    curb_weight: 15000,
    range: 800,
    price: 120.0,
    scenarios: ["载货", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 170,
  },
  {
    name: "Cybertruck",
    brand: "特斯拉",
    category: "中大型",
    curb_weight: 3107,
    range: 547,
    price: 47.5,
    scenarios: ["长途", "载货"],
    status: "待上市",
    material: "不锈钢",
    energy_density: 217,
  },
  {
    name: "起亚EV6",
    brand: "起亚",
    category: "家用紧凑",
    curb_weight: 1975,
    range: 528,
    price: 28.28,
    scenarios: ["城市通勤", "长途"],
    status: "停售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "现代IONIQ 5",
    brand: "现代",
    category: "家用紧凑",
    curb_weight: 1925,
    range: 550,
    price: 26.98,
    scenarios: ["城市通勤", "长途"],
    status: "停售",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "雪佛兰畅巡",
    brand: "雪佛兰",
    category: "家用紧凑",
    curb_weight: 1660,
    range: 518,
    price: 15.99,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 160,
  },
  {
    name: "雪佛兰探界者EV",
    brand: "雪佛兰",
    category: "家用紧凑",
    curb_weight: 2100,
    range: 500,
    price: 22.0,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 180,
  },
  {
    name: "本田e:NS1",
    brand: "本田",
    category: "家用紧凑",
    curb_weight: 1652,
    range: 510,
    price: 17.5,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "丰田bZ4X",
    brand: "丰田",
    category: "家用紧凑",
    curb_weight: 1920,
    range: 615,
    price: 19.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "丰田bZ3",
    brand: "丰田",
    category: "家用紧凑",
    curb_weight: 1710,
    range: 616,
    price: 16.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "日产Ariya",
    brand: "日产",
    category: "家用紧凑",
    curb_weight: 1900,
    range: 533,
    price: 25.28,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "斯巴鲁Solterra",
    brand: "斯巴鲁",
    category: "家用紧凑",
    curb_weight: 2015,
    range: 460,
    price: 29.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "马自达MX-30",
    brand: "马自达",
    category: "家用紧凑",
    curb_weight: 1640,
    range: 356,
    price: 15.98,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 155,
  },
  {
    name: "雪铁龙凡尔赛C5 X PHEV",
    brand: "雪铁龙",
    category: "家用紧凑",
    curb_weight: 1680,
    range: 58,
    price: 23.87,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "标致408X PHEV",
    brand: "标致",
    category: "家用紧凑",
    curb_weight: 1650,
    range: 60,
    price: 22.57,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 140,
  },
  {
    name: "DS 9新能源",
    brand: "DS",
    category: "中大型",
    curb_weight: 1785,
    range: 50,
    price: 33.99,
    scenarios: ["城市通勤"],
    status: "停售",
    material: "高强度钢",
    energy_density: 135,
  },
  {
    name: "极星2",
    brand: "极星",
    category: "中大型",
    curb_weight: 2113,
    range: 675,
    price: 29.98,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "极星3",
    brand: "极星",
    category: "中大型",
    curb_weight: 2640,
    range: 620,
    price: 69.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金",
    energy_density: 195,
  },
  {
    name: "路特斯Eletre",
    brand: "路特斯",
    category: "中大型",
    curb_weight: 2690,
    range: 560,
    price: 82.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "铝合金+碳纤维",
    energy_density: 200,
  },
  {
    name: "保时捷Taycan",
    brand: "保时捷",
    category: "中大型",
    curb_weight: 2295,
    range: 538,
    price: 89.8,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "奥迪RS e-tron GT",
    brand: "奥迪",
    category: "中大型",
    curb_weight: 2420,
    range: 495,
    price: 148.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "奔驰EQE SUV",
    brand: "奔驰",
    category: "中大型",
    curb_weight: 2560,
    range: 609,
    price: 68.0,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "雷克萨斯RX新能源",
    brand: "雷克萨斯",
    category: "中大型",
    curb_weight: 2165,
    range: 600,
    price: 42.5,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 180,
  },
  {
    name: "雷克萨斯RZ450e",
    brand: "雷克萨斯",
    category: "中大型",
    curb_weight: 2115,
    range: 520,
    price: 51.9,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "沃尔沃EX90",
    brand: "沃尔沃",
    category: "中大型",
    curb_weight: 2700,
    range: 600,
    price: 78.0,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "铝合金",
    energy_density: 190,
  },
  {
    name: "沃尔沃EX30",
    brand: "沃尔沃",
    category: "家用紧凑",
    curb_weight: 1720,
    range: 590,
    price: 21.0,
    scenarios: ["城市通勤"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "smart精灵#3",
    brand: "smart",
    category: "家用紧凑",
    curb_weight: 1745,
    range: 520,
    price: 20.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 175,
  },
  {
    name: "smart精灵#5",
    brand: "smart",
    category: "中大型",
    curb_weight: 1980,
    range: 550,
    price: 24.99,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "铝合金",
    energy_density: 185,
  },
  {
    name: "福特野马Mach-E",
    brand: "福特",
    category: "家用紧凑",
    curb_weight: 2188,
    range: 492,
    price: 24.99,
    scenarios: ["城市通勤", "长途"],
    status: "在售",
    material: "高强度钢",
    energy_density: 170,
  },
  {
    name: "福特F-150 Lightning",
    brand: "福特",
    category: "商用",
    curb_weight: 2903,
    range: 515,
    price: 39.98,
    scenarios: ["载货", "长途"],
    status: "在售",
    material: "高强度钢+铝合金",
    energy_density: 180,
  },
  {
    name: "悍马EV",
    brand: "悍马",
    category: "中大型",
    curb_weight: 4103,
    range: 563,
    price: 79.99,
    scenarios: ["长途", "载货"],
    status: "在售",
    material: "高强度钢",
    energy_density: 175,
  },
  {
    name: "雪佛兰Silverado EV",
    brand: "雪佛兰",
    category: "商用",
    curb_weight: 3800,
    range: 640,
    price: 42.0,
    scenarios: ["载货", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "RAM 1500 REV",
    brand: "RAM",
    category: "商用",
    curb_weight: 3700,
    range: 800,
    price: 45.0,
    scenarios: ["载货", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 190,
  },
  {
    name: "Scioniq 7",
    brand: "现代",
    category: "中大型",
    curb_weight: 2400,
    range: 484,
    price: 35.0,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "起亚EV9",
    brand: "起亚",
    category: "中大型",
    curb_weight: 2600,
    range: 541,
    price: 38.0,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
  {
    name: "日产Max-Out",
    brand: "日产",
    category: "中大型",
    curb_weight: 2300,
    range: 500,
    price: 32.0,
    scenarios: ["城市通勤", "长途"],
    status: "待上市",
    material: "高强度钢+铝合金",
    energy_density: 185,
  },
];

const techProgress = [
  {
    type: "material",
    name: "碳纤维复合材料",
    description: "高强度碳纤维复合材料在车身结构中的应用，实现显著减重",
    weight_reduction: 35,
    efficiency_improvement: 20,
    maturity_level: "小批量应用",
  },
  {
    type: "material",
    name: "铝锂合金",
    description: "新型铝锂合金材料，比传统铝合金轻10-15%",
    weight_reduction: 15,
    efficiency_improvement: 8,
    maturity_level: "研发阶段",
  },
  {
    type: "material",
    name: "高强度钢热成型",
    description: "第三代先进高强度钢热成型技术，厚度降低强度提升",
    weight_reduction: 12,
    efficiency_improvement: 6,
    maturity_level: "量产应用",
  },
  {
    type: "material",
    name: "镁合金",
    description: "轻量化镁合金在内饰和结构件中的应用",
    weight_reduction: 25,
    efficiency_improvement: 12,
    maturity_level: "小批量应用",
  },
  {
    type: "material",
    name: "高强度铝合金",
    description: "高真空高压铸造铝合金",
    weight_reduction: 18,
    efficiency_improvement: 10,
    maturity_level: "量产应用",
  },
  {
    type: "material",
    name: "树脂基复合材料",
    description: "纤维增强树脂基复合材料",
    weight_reduction: 30,
    efficiency_improvement: 15,
    maturity_level: "研发阶段",
  },
  {
    type: "material",
    name: "超薄高强钢",
    description: "1500MPa级以上高强度钢",
    weight_reduction: 10,
    efficiency_improvement: 5,
    maturity_level: "量产应用",
  },
  {
    type: "material",
    name: "空心型材",
    description: "铝挤压空心型材结构",
    weight_reduction: 20,
    efficiency_improvement: 10,
    maturity_level: "量产应用",
  },
  {
    type: "battery",
    name: "宁德时代麒麟电池",
    description: "麒麟电池，体积利用率突破72%，能量密度255Wh/kg",
    weight_reduction: 5,
    efficiency_improvement: 15,
    maturity_level: "量产应用",
  },
  {
    type: "battery",
    name: "宁德时代凝聚态电池",
    description: "凝聚态电池，能量密度500Wh/kg级半固态电池",
    weight_reduction: 10,
    efficiency_improvement: 30,
    maturity_level: "小批量应用",
  },
  {
    type: "battery",
    name: "4680圆柱电池",
    description: "4680大圆柱电池，能量密度提升16%",
    weight_reduction: 8,
    efficiency_improvement: 12,
    maturity_level: "量产应用",
  },
  {
    type: "battery",
    name: "半固态电池",
    description: "半固态电解质电池，能量密度360Wh/kg",
    weight_reduction: 12,
    efficiency_improvement: 25,
    maturity_level: "小批量应用",
  },
  {
    type: "battery",
    name: "固态电池",
    description: "全固态电池，能量密度400-500Wh/kg",
    weight_reduction: 15,
    efficiency_improvement: 35,
    maturity_level: "研发阶段",
  },
  {
    type: "battery",
    name: "高镍三元电池",
    description: "NCM811高镍三元材料",
    weight_reduction: 5,
    efficiency_improvement: 10,
    maturity_level: "量产应用",
  },
  {
    type: "battery",
    name: "磷酸锰铁锂",
    description: "磷酸锰铁锂电池，能量密度提升15%",
    weight_reduction: 3,
    efficiency_improvement: 8,
    maturity_level: "小批量应用",
  },
  {
    type: "battery",
    name: "无钴电池",
    description: "无钴电池材料技术",
    weight_reduction: 4,
    efficiency_improvement: 8,
    maturity_level: "研发阶段",
  },
  {
    type: "structure",
    name: "CTC电池车身一体化",
    description: "电池底盘一体化技术，取消电池包外壳",
    weight_reduction: 10,
    efficiency_improvement: 8,
    maturity_level: "量产应用",
  },
  {
    type: "structure",
    name: "CTB电池车身一体化",
    description: "比亚迪CTB技术，刀片电池与车身地板集成",
    weight_reduction: 8,
    efficiency_improvement: 6,
    maturity_level: "量产应用",
  },
  {
    type: "structure",
    name: "铝合金压铸一体化",
    description: "大型一体化压铸车身结构件",
    weight_reduction: 15,
    efficiency_improvement: 10,
    maturity_level: "量产应用",
  },
  {
    type: "structure",
    name: "线控底盘",
    description: "线控转向、线控制动，取消机械连接",
    weight_reduction: 8,
    efficiency_improvement: 5,
    maturity_level: "小批量应用",
  },
  {
    type: "structure",
    name: "滑板底盘",
    description: "集成式滑板底盘架构",
    weight_reduction: 12,
    efficiency_improvement: 8,
    maturity_level: "研发阶段",
  },
  {
    type: "structure",
    name: "一体化热管理",
    description: "八合一电动力总成",
    weight_reduction: 10,
    efficiency_improvement: 12,
    maturity_level: "量产应用",
  },
  {
    type: "structure",
    name: "SiC碳化硅",
    description: "碳化硅功率半导体，系统效率提升8%",
    weight_reduction: 3,
    efficiency_improvement: 8,
    maturity_level: "量产应用",
  },
  {
    type: "structure",
    name: "800V高压平台",
    description: "800V高压电驱系统",
    weight_reduction: 5,
    efficiency_improvement: 10,
    maturity_level: "量产应用",
  },
];

function initVehicles() {
  console.log("开始初始化车型数据...");

  const stmt = db.prepare(`INSERT INTO vehicles 
    (name, brand, category, curb_weight, range, price, scenarios, status, material, energy_density, launch_year)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

  db.serialize(() => {
    db.run("BEGIN TRANSACTION");

    vehicles.forEach((v, index) => {
      const launchYear = v.launch_year || vehicleLaunchYears[v.name] || 2023;
      stmt.run(
        v.name,
        v.brand,
        v.category,
        v.curb_weight,
        v.range,
        v.price,
        JSON.stringify(v.scenarios),
        v.status,
        v.material,
        v.energy_density,
        launchYear,
        function (err) {
          if (err) {
            console.error(`插入车型 ${v.name} 失败:`, err.message);
          }
        },
      );
      if ((index + 1) % 20 === 0) {
        console.log(`已插入 ${index + 1}/${vehicles.length} 条车型数据`);
      }
    });

    db.run("COMMIT", (err) => {
      if (err) {
        console.error("提交事务失败:", err.message);
      } else {
        console.log(`✓ 成功插入 ${vehicles.length} 条车型数据`);
      }
      stmt.finalize();
    });
  });
}

function initTechProgress() {
  console.log("\n开始初始化技术进展数据...");

  const stmt = db.prepare(`INSERT INTO tech_progress 
    (type, name, description, weight_reduction, efficiency_improvement, maturity_level)
    VALUES (?, ?, ?, ?, ?, ?)`);

  db.serialize(() => {
    db.run("BEGIN TRANSACTION");

    techProgress.forEach((tech, index) => {
      stmt.run(
        tech.type,
        tech.name,
        tech.description,
        tech.weight_reduction,
        tech.efficiency_improvement,
        tech.maturity_level,
        function (err) {
          if (err) {
            console.error(`插入技术 ${tech.name} 失败:`, err.message);
          }
        },
      );
      if ((index + 1) % 5 === 0) {
        console.log(`已插入 ${index + 1}/${techProgress.length} 条技术数据`);
      }
    });

    db.run("COMMIT", (err) => {
      if (err) {
        console.error("提交事务失败:", err.message);
      } else {
        console.log(`✓ 成功插入 ${techProgress.length} 条技术数据`);
      }
      stmt.finalize();
    });
  });
}

function initTierTrendStats() {
  console.log("\n开始生成分档趋势统计数据...");

  const weightTiers = [
    { name: "<1200kg", min: 0, max: 1200 },
    { name: "1200-1500kg", min: 1200, max: 1500 },
    { name: "1500-1800kg", min: 1500, max: 1800 },
    { name: "1800-2200kg", min: 1800, max: 2200 },
    { name: "2200-2800kg", min: 2200, max: 2800 },
    { name: ">=2800kg", min: 2800, max: Infinity },
  ];

  const months = [];
  const now = new Date();
  for (let i = 11; i >= 0; i--) {
    const d = new Date(now.getFullYear(), now.getMonth() - i, 1);
    months.push(d.toISOString().slice(0, 7));
  }

  const stmt = db.prepare(`INSERT INTO tier_trend_stats 
    (stat_date, tier_name, vehicle_count, indicator_type)
    VALUES (?, ?, ?, ?)`);

  db.serialize(() => {
    db.run("BEGIN TRANSACTION");

    months.forEach((month, monthIdx) => {
      const progress = (monthIdx + 1) / months.length;

      weightTiers.forEach((tier) => {
        const baseCount = vehicles.filter(
          (v) =>
            v.curb_weight >= tier.min &&
            v.curb_weight < tier.max &&
            v.status === "在售",
        ).length;

        const growthFactor = 0.4 + progress * 0.6;
        const randomVariation = 0.85 + Math.random() * 0.3;
        const count = Math.max(
          0,
          Math.round(baseCount * growthFactor * randomVariation),
        );

        stmt.run(month, tier.name, count, "weight", (err) => {
          if (err) {
            console.error(
              `插入分档趋势数据 ${month} ${tier.name} 失败:`,
              err.message,
            );
          }
        });
      });
    });

    db.run("COMMIT", (err) => {
      if (err) {
        console.error("提交事务失败:", err.message);
      } else {
        console.log(`✓ 成功生成分档趋势统计数据`);
      }
      stmt.finalize();
    });
  });
}

const regions = [
  {
    name: "华北平原地区",
    code: "north-plain",
    terrain_type: "平原",
    climate: "温带季风气候",
    typical_usage: "城市通勤、城际长途",
    description: "地势平坦，道路条件好，适合各类车型，冬季较冷对续航有一定影响",
  },
  {
    name: "长三角地区",
    code: "yangtze-delta",
    terrain_type: "平原",
    climate: "亚热带季风气候",
    typical_usage: "城市通勤、商务出行",
    description: "经济发达，城市拥堵严重，新能源汽车普及度高，充电设施完善",
  },
  {
    name: "珠三角地区",
    code: "pearl-delta",
    terrain_type: "平原",
    climate: "亚热带季风气候",
    typical_usage: "城市通勤、城际通勤",
    description: "气候温暖，全年气温高，对电池友好，城市密集，通勤需求大",
  },
  {
    name: "西南山区",
    code: "southwest-mountain",
    terrain_type: "山区",
    climate: "亚热带高原气候",
    typical_usage: "山路行驶、爬坡需求",
    description: "地形复杂，多山路陡坡，对动力性能和车身轻量化要求高",
  },
  {
    name: "川渝地区",
    code: "sichuan-chongqing",
    terrain_type: "丘陵",
    climate: "亚热带季风气候",
    typical_usage: "城市通勤、山路行驶",
    description: "多山地丘陵，道路起伏大，城市拥堵严重，需要强劲动力和高效率",
  },
  {
    name: "西北地区",
    code: "northwest",
    terrain_type: "高原",
    climate: "温带大陆性气候",
    typical_usage: "长途运输、城际出行",
    description: "地域广阔，城市间距大，冬季寒冷，需要长续航和良好的低温性能",
  },
  {
    name: "东北地区",
    code: "northeast",
    terrain_type: "平原",
    climate: "温带季风气候",
    typical_usage: "城市通勤、短途运输",
    description: "冬季严寒漫长，低温对电池影响大，需要优良的温控系统",
  },
  {
    name: "北上广深超大城市",
    code: "megacities",
    terrain_type: "城市拥堵",
    climate: "多样",
    typical_usage: "城市通勤、代步出行",
    description: "城市拥堵严重，停车空间紧张，需求微型、紧凑级轻量化车型",
  },
];

const regionRequirements = {
  "north-plain": [
    {
      category: "微型代步",
      min_range: 200,
      max_weight: 1200,
      max_price: 8,
      priority: 3,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 400,
      max_weight: 2000,
      max_price: 25,
      priority: 1,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "中大型",
      min_range: 500,
      max_weight: 2800,
      max_price: 50,
      priority: 2,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 250,
      min_weight: 1500,
      max_price: 30,
      priority: 2,
      required_scenarios: ["载货"],
    },
  ],
  "yangtze-delta": [
    {
      category: "微型代步",
      min_range: 250,
      max_weight: 1100,
      max_price: 10,
      priority: 2,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 450,
      max_weight: 1900,
      max_price: 30,
      priority: 1,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "中大型",
      min_range: 550,
      max_weight: 2600,
      max_price: 60,
      priority: 2,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 280,
      min_weight: 1500,
      max_price: 35,
      priority: 3,
      required_scenarios: ["载货"],
    },
  ],
  "pearl-delta": [
    {
      category: "微型代步",
      min_range: 250,
      max_weight: 1100,
      max_price: 8,
      priority: 1,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 400,
      max_weight: 1800,
      max_price: 25,
      priority: 1,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "中大型",
      min_range: 500,
      max_weight: 2500,
      max_price: 50,
      priority: 3,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 300,
      min_weight: 1500,
      max_price: 30,
      priority: 2,
      required_scenarios: ["载货"],
    },
  ],
  "southwest-mountain": [
    {
      category: "微型代步",
      min_range: 200,
      max_weight: 1100,
      max_price: 8,
      priority: 3,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 450,
      min_weight: 1400,
      max_weight: 2000,
      max_price: 28,
      priority: 1,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "中大型",
      min_range: 600,
      min_weight: 1800,
      max_weight: 2700,
      max_price: 55,
      priority: 2,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 300,
      min_weight: 2000,
      max_price: 35,
      priority: 1,
      required_scenarios: ["载货"],
    },
  ],
  "sichuan-chongqing": [
    {
      category: "微型代步",
      min_range: 200,
      max_weight: 1100,
      max_price: 8,
      priority: 2,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 400,
      min_weight: 1400,
      max_weight: 1900,
      max_price: 25,
      priority: 1,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "中大型",
      min_range: 550,
      min_weight: 1800,
      max_weight: 2600,
      max_price: 50,
      priority: 2,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 280,
      min_weight: 1800,
      max_price: 32,
      priority: 2,
      required_scenarios: ["载货"],
    },
  ],
  northwest: [
    {
      category: "微型代步",
      min_range: 250,
      max_weight: 1200,
      max_price: 8,
      priority: 4,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 550,
      max_weight: 2000,
      max_price: 30,
      priority: 2,
      required_scenarios: ["长途"],
    },
    {
      category: "中大型",
      min_range: 650,
      min_weight: 1800,
      max_weight: 2800,
      max_price: 60,
      priority: 1,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 350,
      min_weight: 2500,
      max_price: 50,
      priority: 1,
      required_scenarios: ["载货", "长途"],
    },
  ],
  northeast: [
    {
      category: "微型代步",
      min_range: 200,
      max_weight: 1200,
      max_price: 7,
      priority: 3,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 450,
      max_weight: 2000,
      max_price: 25,
      priority: 1,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "中大型",
      min_range: 550,
      max_weight: 2700,
      max_price: 50,
      priority: 2,
      required_scenarios: ["长途"],
    },
    {
      category: "商用",
      min_range: 250,
      min_weight: 2000,
      max_price: 30,
      priority: 2,
      required_scenarios: ["载货"],
    },
  ],
  megacities: [
    {
      category: "微型代步",
      min_range: 200,
      max_weight: 1000,
      max_price: 8,
      priority: 1,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "家用紧凑",
      min_range: 400,
      max_weight: 1800,
      max_price: 30,
      priority: 1,
      required_scenarios: ["城市通勤"],
    },
    {
      category: "中大型",
      min_range: 500,
      max_weight: 2500,
      max_price: 70,
      priority: 3,
      required_scenarios: ["城市通勤", "长途"],
    },
    {
      category: "商用",
      min_range: 250,
      max_weight: 3000,
      max_price: 35,
      priority: 2,
      required_scenarios: ["载货", "城市通勤"],
    },
  ],
};

function initRegions() {
  console.log("\n开始初始化地域数据...");

  const regionStmt = db.prepare(`INSERT INTO regions 
    (name, code, terrain_type, climate, typical_usage, description)
    VALUES (?, ?, ?, ?, ?, ?)`);

  const reqStmt = db.prepare(`INSERT INTO region_vehicle_requirements 
    (region_id, category, min_range, max_range, min_weight, max_weight, min_price, max_price, terrain_suitability, priority, required_scenarios)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

  db.serialize(() => {
    db.run("BEGIN TRANSACTION");

    regions.forEach((region, index) => {
      regionStmt.run(
        region.name,
        region.code,
        region.terrain_type,
        region.climate,
        region.typical_usage,
        region.description,
        function (err) {
          if (err) {
            console.error(`插入地区 ${region.name} 失败:`, err.message);
            return;
          }
          const regionId = this.lastID;
          const reqs = regionRequirements[region.code] || [];
          reqs.forEach((req) => {
            reqStmt.run(
              regionId,
              req.category,
              req.min_range || null,
              req.max_range || null,
              req.min_weight || null,
              req.max_weight || null,
              req.min_price || null,
              req.max_price || null,
              region.terrain_type,
              req.priority || 0,
              req.required_scenarios
                ? JSON.stringify(req.required_scenarios)
                : null,
              (err) => {
                if (err) {
                  console.error(`插入地区需求失败:`, err.message);
                }
              },
            );
          });
        },
      );
      if ((index + 1) % 4 === 0) {
        console.log(`已插入 ${index + 1}/${regions.length} 个地区`);
      }
    });

    db.run("COMMIT", (err) => {
      if (err) {
        console.error("提交事务失败:", err.message);
      } else {
        console.log(`✓ 成功插入 ${regions.length} 个地区及需求数据`);
      }
      regionStmt.finalize();
      reqStmt.finalize();
    });
  });
}

function initAnnualDiversityStats() {
  console.log("\n开始生成年度多元化统计数据...");

  const years = [2020, 2021, 2022, 2023, 2024, 2025];
  const categoryMap = {
    微型代步: "micro",
    家用紧凑: "compact",
    中大型: "midsize",
    商用: "commercial",
  };

  const stmt = db.prepare(`INSERT OR REPLACE INTO annual_diversity_stats 
    (stat_year, total_vehicles, diversity_score, micro_count, compact_count, midsize_count, commercial_count,
     micro_ratio, compact_ratio, midsize_ratio, commercial_ratio, avg_weight, heavy_ratio, brand_count)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`);

  db.serialize(() => {
    db.run("BEGIN TRANSACTION");

    years.forEach((year, yearIdx) => {
      const yearProgress = (yearIdx + 1) / years.length;
      const yearVehicles = vehicles.filter(
        (v) =>
          (v.launch_year || vehicleLaunchYears[v.name] || 2023) <= year &&
          v.status !== "停售",
      );

      const total = yearVehicles.length;
      const categoryCounts = {
        micro: 0,
        compact: 0,
        midsize: 0,
        commercial: 0,
      };
      let totalWeight = 0;
      let heavyCount = 0;
      const brands = new Set();

      yearVehicles.forEach((v) => {
        const catKey = categoryMap[v.category];
        if (catKey) categoryCounts[catKey]++;
        totalWeight += v.curb_weight;
        if (v.curb_weight >= 1800) heavyCount++;
        brands.add(v.brand);
      });

      const baseRatios = {
        2020: { micro: 35, compact: 30, midsize: 20, commercial: 15 },
        2021: { micro: 32, compact: 33, midsize: 22, commercial: 13 },
        2022: { micro: 28, compact: 35, midsize: 25, commercial: 12 },
        2023: { micro: 24, compact: 36, midsize: 28, commercial: 12 },
        2024: { micro: 20, compact: 37, midsize: 30, commercial: 13 },
        2025: { micro: 18, compact: 38, midsize: 32, commercial: 12 },
      };

      const ratios = baseRatios[year] || baseRatios[2024];
      const scaledTotal = Math.round(20 + yearProgress * 140);
      const microCount = Math.round(scaledTotal * (ratios.micro / 100));
      const compactCount = Math.round(scaledTotal * (ratios.compact / 100));
      const midsizeCount = Math.round(scaledTotal * (ratios.midsize / 100));
      const commercialCount =
        scaledTotal - microCount - compactCount - midsizeCount;

      const simulatedTotal =
        microCount + compactCount + midsizeCount + commercialCount;
      const microRatio = (microCount / simulatedTotal) * 100;
      const compactRatio = (compactCount / simulatedTotal) * 100;
      const midsizeRatio = (midsizeCount / simulatedTotal) * 100;
      const commercialRatio = (commercialCount / simulatedTotal) * 100;

      const expectedPerCategory = simulatedTotal / 4;
      const maxDeviation =
        Math.max(
          Math.abs(microCount - expectedPerCategory) / expectedPerCategory,
          Math.abs(compactCount - expectedPerCategory) / expectedPerCategory,
          Math.abs(midsizeCount - expectedPerCategory) / expectedPerCategory,
          Math.abs(commercialCount - expectedPerCategory) / expectedPerCategory,
        ) * 100;

      const baseDiversity = 55 + yearProgress * 25;
      const diversityScore = Math.max(
        0,
        Math.min(100, baseDiversity - maxDeviation * 0.3),
      );

      const baseHeavyRatio = 30 + yearProgress * 15;
      const avgWeight = 1400 + yearProgress * 400;
      const brandCount = 8 + Math.round(yearProgress * 22);

      stmt.run(
        year,
        simulatedTotal,
        parseFloat(diversityScore.toFixed(1)),
        microCount,
        compactCount,
        midsizeCount,
        commercialCount,
        parseFloat(microRatio.toFixed(1)),
        parseFloat(compactRatio.toFixed(1)),
        parseFloat(midsizeRatio.toFixed(1)),
        parseFloat(commercialRatio.toFixed(1)),
        parseFloat(avgWeight.toFixed(1)),
        parseFloat(baseHeavyRatio.toFixed(1)),
        brandCount,
        (err) => {
          if (err) {
            console.error(`插入年度统计 ${year} 失败:`, err.message);
          }
        },
      );

      console.log(`已生成 ${year} 年度多元化统计数据`);
    });

    db.run("COMMIT", (err) => {
      if (err) {
        console.error("提交事务失败:", err.message);
      } else {
        console.log(`✓ 成功生成 ${years.length} 年年度多元化统计数据`);
      }
      stmt.finalize();
      console.log("\n数据初始化完成！");
      setTimeout(() => db.close(), 100);
    });
  });
}

function clearAndInit() {
  console.log("初始化数据表...");
  initTables();

  setTimeout(() => {
    console.log("清空现有数据...");
    db.serialize(() => {
      db.run("DELETE FROM vehicles");
      db.run("DELETE FROM tech_progress");
      db.run("DELETE FROM tier_trend_stats");
      db.run("DELETE FROM annual_diversity_stats");
      db.run("DELETE FROM region_vehicle_requirements");
      db.run("DELETE FROM regions");
      db.run(
        'DELETE FROM sqlite_sequence WHERE name IN ("vehicles", "tech_progress", "tier_trend_stats", "annual_diversity_stats", "regions", "region_vehicle_requirements")',
        (err) => {
          if (err) {
            console.error("清空数据失败:", err.message);
          } else {
            console.log("数据清空完成");
            initVehicles();
            setTimeout(() => {
              initTechProgress();
              setTimeout(() => {
                initTierTrendStats();
                setTimeout(() => {
                  initRegions();
                  setTimeout(initAnnualDiversityStats, 1000);
                }, 1000);
              }, 1000);
            }, 1000);
          }
        },
      );
    });
  }, 500);
}

clearAndInit();
